CREATE DATABASE IF NOT EXISTS certhub;
USE certhub;

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role ENUM('STUDENT', 'TEACHER', 'ADMIN') NOT NULL,
  avatar VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS certificates (
  id VARCHAR(255) PRIMARY KEY,
  student_id VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  platform VARCHAR(255) NOT NULL,
  issued_date DATE NOT NULL,
  file_url TEXT NOT NULL,
  status ENUM('PENDING', 'VERIFIED', 'REJECTED') DEFAULT 'PENDING',
  remarks TEXT,
  verified_by VARCHAR(255),
  verified_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE
);
